# Generated by Django 4.2.13 on 2024-05-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_performances_alter_group_title_alter_soloists_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], verbose_name='Номер по порядку')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Группа')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.performances', verbose_name='Выступление')),
                ('solist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.soloists', verbose_name='Солист')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['number'],
            },
        ),
    ]
