# Generated by Django 4.2.13 on 2024-05-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_group_options_alter_performances_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='group_2',
        ),
    ]
