# Generated by Django 4.2.13 on 2024-05-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_schedules_group_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='schedule.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='solist',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='schedule.soloists', verbose_name='Солисты'),
        ),
    ]
